# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Volumes/Extreme SSD/roguelikeexperiment/RogueLikeExperiment/Rogue Style Game"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Volumes/Extreme SSD/roguelikeexperiment/RogueLikeExperiment"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Volumes/Extreme SSD/roguelikeexperiment/RogueLikeExperiment/CMakeFiles" "/Volumes/Extreme SSD/roguelikeexperiment/RogueLikeExperiment//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Volumes/Extreme SSD/roguelikeexperiment/RogueLikeExperiment/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RogueGame

# Build rule for target.
RogueGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RogueGame
.PHONY : RogueGame

# fast build rule for target.
RogueGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/build
.PHONY : RogueGame/fast

src/Coords.o: src/Coords.cpp.o
.PHONY : src/Coords.o

# target to build an object file
src/Coords.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Coords.cpp.o
.PHONY : src/Coords.cpp.o

src/Coords.i: src/Coords.cpp.i
.PHONY : src/Coords.i

# target to preprocess a source file
src/Coords.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Coords.cpp.i
.PHONY : src/Coords.cpp.i

src/Coords.s: src/Coords.cpp.s
.PHONY : src/Coords.s

# target to generate assembly for a file
src/Coords.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Coords.cpp.s
.PHONY : src/Coords.cpp.s

src/Enemies/Enemy.o: src/Enemies/Enemy.cpp.o
.PHONY : src/Enemies/Enemy.o

# target to build an object file
src/Enemies/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Enemies/Enemy.cpp.o
.PHONY : src/Enemies/Enemy.cpp.o

src/Enemies/Enemy.i: src/Enemies/Enemy.cpp.i
.PHONY : src/Enemies/Enemy.i

# target to preprocess a source file
src/Enemies/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Enemies/Enemy.cpp.i
.PHONY : src/Enemies/Enemy.cpp.i

src/Enemies/Enemy.s: src/Enemies/Enemy.cpp.s
.PHONY : src/Enemies/Enemy.s

# target to generate assembly for a file
src/Enemies/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Enemies/Enemy.cpp.s
.PHONY : src/Enemies/Enemy.cpp.s

src/GameManager.o: src/GameManager.cpp.o
.PHONY : src/GameManager.o

# target to build an object file
src/GameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/GameManager.cpp.o
.PHONY : src/GameManager.cpp.o

src/GameManager.i: src/GameManager.cpp.i
.PHONY : src/GameManager.i

# target to preprocess a source file
src/GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/GameManager.cpp.i
.PHONY : src/GameManager.cpp.i

src/GameManager.s: src/GameManager.cpp.s
.PHONY : src/GameManager.s

# target to generate assembly for a file
src/GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/GameManager.cpp.s
.PHONY : src/GameManager.cpp.s

src/Items/Item.o: src/Items/Item.cpp.o
.PHONY : src/Items/Item.o

# target to build an object file
src/Items/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Items/Item.cpp.o
.PHONY : src/Items/Item.cpp.o

src/Items/Item.i: src/Items/Item.cpp.i
.PHONY : src/Items/Item.i

# target to preprocess a source file
src/Items/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Items/Item.cpp.i
.PHONY : src/Items/Item.cpp.i

src/Items/Item.s: src/Items/Item.cpp.s
.PHONY : src/Items/Item.s

# target to generate assembly for a file
src/Items/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Items/Item.cpp.s
.PHONY : src/Items/Item.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Map.o: src/Map.cpp.o
.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i
.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s
.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/MapGenerator.o: src/MapGenerator.cpp.o
.PHONY : src/MapGenerator.o

# target to build an object file
src/MapGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/MapGenerator.cpp.o
.PHONY : src/MapGenerator.cpp.o

src/MapGenerator.i: src/MapGenerator.cpp.i
.PHONY : src/MapGenerator.i

# target to preprocess a source file
src/MapGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/MapGenerator.cpp.i
.PHONY : src/MapGenerator.cpp.i

src/MapGenerator.s: src/MapGenerator.cpp.s
.PHONY : src/MapGenerator.s

# target to generate assembly for a file
src/MapGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/MapGenerator.cpp.s
.PHONY : src/MapGenerator.cpp.s

src/Pathfinding/PathPointNode.o: src/Pathfinding/PathPointNode.cpp.o
.PHONY : src/Pathfinding/PathPointNode.o

# target to build an object file
src/Pathfinding/PathPointNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Pathfinding/PathPointNode.cpp.o
.PHONY : src/Pathfinding/PathPointNode.cpp.o

src/Pathfinding/PathPointNode.i: src/Pathfinding/PathPointNode.cpp.i
.PHONY : src/Pathfinding/PathPointNode.i

# target to preprocess a source file
src/Pathfinding/PathPointNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Pathfinding/PathPointNode.cpp.i
.PHONY : src/Pathfinding/PathPointNode.cpp.i

src/Pathfinding/PathPointNode.s: src/Pathfinding/PathPointNode.cpp.s
.PHONY : src/Pathfinding/PathPointNode.s

# target to generate assembly for a file
src/Pathfinding/PathPointNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Pathfinding/PathPointNode.cpp.s
.PHONY : src/Pathfinding/PathPointNode.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/ProjectSettings.o: src/ProjectSettings.cpp.o
.PHONY : src/ProjectSettings.o

# target to build an object file
src/ProjectSettings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/ProjectSettings.cpp.o
.PHONY : src/ProjectSettings.cpp.o

src/ProjectSettings.i: src/ProjectSettings.cpp.i
.PHONY : src/ProjectSettings.i

# target to preprocess a source file
src/ProjectSettings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/ProjectSettings.cpp.i
.PHONY : src/ProjectSettings.cpp.i

src/ProjectSettings.s: src/ProjectSettings.cpp.s
.PHONY : src/ProjectSettings.s

# target to generate assembly for a file
src/ProjectSettings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/ProjectSettings.cpp.s
.PHONY : src/ProjectSettings.cpp.s

src/Room.o: src/Room.cpp.o
.PHONY : src/Room.o

# target to build an object file
src/Room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Room.cpp.o
.PHONY : src/Room.cpp.o

src/Room.i: src/Room.cpp.i
.PHONY : src/Room.i

# target to preprocess a source file
src/Room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Room.cpp.i
.PHONY : src/Room.cpp.i

src/Room.s: src/Room.cpp.s
.PHONY : src/Room.s

# target to generate assembly for a file
src/Room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RogueGame.dir/build.make CMakeFiles/RogueGame.dir/src/Room.cpp.s
.PHONY : src/Room.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RogueGame"
	@echo "... src/Coords.o"
	@echo "... src/Coords.i"
	@echo "... src/Coords.s"
	@echo "... src/Enemies/Enemy.o"
	@echo "... src/Enemies/Enemy.i"
	@echo "... src/Enemies/Enemy.s"
	@echo "... src/GameManager.o"
	@echo "... src/GameManager.i"
	@echo "... src/GameManager.s"
	@echo "... src/Items/Item.o"
	@echo "... src/Items/Item.i"
	@echo "... src/Items/Item.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/MapGenerator.o"
	@echo "... src/MapGenerator.i"
	@echo "... src/MapGenerator.s"
	@echo "... src/Pathfinding/PathPointNode.o"
	@echo "... src/Pathfinding/PathPointNode.i"
	@echo "... src/Pathfinding/PathPointNode.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/ProjectSettings.o"
	@echo "... src/ProjectSettings.i"
	@echo "... src/ProjectSettings.s"
	@echo "... src/Room.o"
	@echo "... src/Room.i"
	@echo "... src/Room.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

